### ISSUE TITLE
Mangony watcher doesn't find existing folders and files on Windows 10 Pro. 

### ISSUE THREAD

**Issue by picadu** [Sebastian-Fitzner/mangony#4]
mangony@1.5.1

The mangony watcher doesn't find existing folders and files on Windows 10 Pro and wont detect changes in my template files. But when I user an absolute path in my mangony.config.js (without any *), the watcher is working:
`
not working: 'app/pages/**/*.hbs',
working: 'app/pages/index/index.hbs',
`

![image](https://user-images.githubusercontent.com/12181343/47142446-2b32b800-d2c3-11e8-9101-4197ababdae5.png)
![image](https://user-images.githubusercontent.com/12181343/47142667-b6ac4900-d2c3-11e8-966c-68f0bca04267.png)

**Comment by Sebastian-Fitzner** [comment]
Will fix it in the upcoming release ... so in a couple of days!

**Comment by Sebastian-Fitzner** [comment]
Issue is fixed in version 1.6.0! Tested on windows 10 machine ... 
Watcher should now work with glob pattern.
