### ISSUE TITLE
(!) Files not compiled

### ISSUE THREAD

**Issue by natrenakres** [Sebastian-Fitzner/mangony#5]
Hi,

Probably Our hbs or hjson files have a problem but we cannot find the which file. Mongony returns just this error 

> (!) Files not compiled: Error: with doesn't match content - 191:3

It tells us that we have a problem in one file but it doesn't say which one of them. We have tons of files in project and now we stuckt. In the detailed error has fileName property but just say undefined. So how can we find problematic fileName?

Script: `node configs/tasks/mangony/mangony-build.js`
`const Mangony = require('mangony');
const mangonyConfig = require('./mangony.config');
const options = Object.assign(mangonyConfig.dist.options, mangonyConfig.options);
const mangony = new Mangony(options);
mangony.render();`

Config Script:
`'use strict';
const globby = require('globby');
const config = require('../../../veams-cli');
const pages = globby.sync([
	`${config.paths.src}/pages/**/*.hbs`,
	`${config.paths.src}/shared/components/**/templates/**/*.hbs`,
	`${config.paths.src}/core/components/**/templates/**/*.hbs`,
	// 'features/**/*.hbs',
	`${config.paths.src}/shared/utilities/**/templates/**/*.hbs`
]).map(item => item.replace(`${config.paths.src}/`, ''));

module.exports = {
	options: {
		allow: {
			YFMContextData: true,
			YFMLayout: true
		},
		collections: [
			'sitemap',
			'type'
		],
		cwd: config.paths.src + '/',
		dest: config.paths.app,
		exportData: false,
		flatten: true,
		types: {
			data: {
				dir: '',
				files: [
					'core/**/*.hjson',
					'core/**/*.json',
					// 'features/**/*.hjson',
					// 'features/**/*.json',
					'shared/components/**/*.hjson',
					'shared/components/**/*.json',
					'pages/**/*.hjson',
					'pages/**/*.json',
					'shared/utilities/**/*.hjson',
					'shared/utilities/**/*.json'
				]
			},
			partials: {
				dir: '',
				files: [
					'shared/components/**/*.hbs',
					'core/components/**/*.hbs',
					// 'core/docs/components/**/*.hbs',
					// 'features/**/*.hbs',
					'shared/utilities/**/*.hbs'
				]
			},
			pages: {
				dir: '',
				files: pages
			},
			layouts: {
				dir: 'core',
				files: [
					'layouts/*.hbs',
					'docs/layouts/*.hbs'
				]
			}
		},
		helpers: [
			'shared/utilities/template-helpers/*.js'
		]
	},
	dev: {
		options: {
			compileStaticFiles: false,
			devServer: {
				start: true,
				injectScript: false,
				useExt: true,
				port: config.ports.server,
				bsOptions: {
					proxy: 'localhost:' + config.ports.server,
					port: config.ports.app,
					files: [
						config.paths.app + '/**/*.html',
						config.paths.app + '/css/**/*.css',
						config.paths.app + '/scripts/**/*.js'
					]
				}
			},
			watch: true
		}
	},
	dist: {
		options: {
			compileStaticFiles: true,
			watch: false
		}
	}
};`

Detailed Error:

> { Error: with doesn't match content - 191:3
    at validateClose (D:\Projects\Lmu Projects\relaunch-web-frontend\node_modules\handlebars\dist\cjs\handlebars\compiler\helpers.js:28:11)
    at Object.prepareBlock (D:\Projects\Lmu Projects\relaunch-web-frontend\node_modules\handlebars\dist\cjs\handlebars\compiler\helpers.js:144:5)
    at Object.anonymous (D:\Projects\Lmu Projects\relaunch-web-frontend\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:66:33)
    at Parser.parse (D:\Projects\Lmu Projects\relaunch-web-frontend\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:368:48)
    at HandlebarsEnvironment.parse (D:\Projects\Lmu Projects\relaunch-web-frontend\node_modules\handlebars\dist\cjs\handlebars\compiler\base.js:46:43)
    at compileInput (D:\Projects\Lmu Projects\relaunch-web-frontend\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:515:19)
    at ret (D:\Projects\Lmu Projects\relaunch-web-frontend\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:524:18)
    at Templater.renderOne (D:\Projects\Lmu Projects\relaunch-web-frontend\node_modules\mangony\lib\plugins\templater.js:159:64)
    at Promise.map (D:\Projects\Lmu Projects\relaunch-web-frontend\node_modules\mangony\lib\plugins\templater.js:98:16)
    at tryCatcher (D:\Projects\Lmu Projects\relaunch-web-frontend\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (D:\Projects\Lmu Projects\relaunch-web-frontend\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (D:\Projects\Lmu Projects\relaunch-web-frontend\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (D:\Projects\Lmu Projects\relaunch-web-frontend\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (D:\Projects\Lmu Projects\relaunch-web-frontend\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (D:\Projects\Lmu Projects\relaunch-web-frontend\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (D:\Projects\Lmu Projects\relaunch-web-frontend\node_modules\bluebird\js\release\async.js:143:10)
  description: undefined,
  **fileName: undefined,**
  lineNumber: 191,
  message: 'with doesn\'t match content - 191:3',
  name: 'Error',
  number: undefined,
  column: 3 }

(!) Files not compiled: Error: with doesn't match content - 191:3

**Comment by Sebastian-Fitzner** [comment]
I can extend the error message... prepare a release until tomorrow.

**Comment by natrenakres** [comment]
any update?

**Comment by Sebastian-Fitzner** [comment]
The latest version (1.6.1) has now a debug support as option. When set to `true` you will get more comments printed out to the terminal. In your case you see the following lines which tells you that the compiling process of a specific page has started. When you have no `Finished` comment it means this file couldn't be compiled, see: 

``` bash
*** Started Mangony Watcher ***

Mangony Watcher :: Added watcher for Mangony:partials
Mangony Watcher :: Added watcher for Mangony:layouts
Mangony Watcher :: Added watcher for Mangony:pages
Mangony Watcher :: Added watcher for Mangony:data
OK: All files are saved!
Got all files in: 146.575ms
OK: All files are cached!
Cached all files in: 49.994ms
Registered files in: 1.815ms

*** Compiling started ... ***

------- Starting to compile test/expected/a.html ... -------
------- Finished compiling of test/expected/a.html! ------- 

------- Starting to compile test/expected/helpers.html ... -------

(!) Files not compiled: TypeError: Cannot read property 'fn' of undefined
Writing test/fixtures/exported/exported-data.json ...
Writing test/expected/a.html ...
Initial file scan for Mangony:layouts is done!
Writing test/fixtures/exported/watcher-Mangony:layouts.json ...
Initial file scan for Mangony:partials is done!
Initial file scan for Mangony:data is done!
Writing test/fixtures/exported/watcher-Mangony:partials.json ...
Writing test/fixtures/exported/watcher-Mangony:data.json ...
Initial file scan for Mangony:pages is done!
Writing test/fixtures/exported/watcher-Mangony:pages.json ...
```

To enable that in your options, see your updated example below: 

``` js

'use strict'; const globby = require('globby'); const config = require('../../../veams-cli'); const pages = globby.sync([ ${config.paths.src}/pages//*.hbs, ${config.paths.src}/shared/components//templates//*.hbs, ${config.paths.src}/core/components//templates//*.hbs, // 'features/**/*.hbs', ${config.paths.src}/shared/utilities//templates/**/*.hbs ]).map(item => item.replace(${config.paths.src}/`, ''));

module.exports = {
	options: {
		allow: {
			YFMContextData: true,
			YFMLayout: true
		},
		collections: [
			'sitemap',
			'type'
		],
		cwd: config.paths.src + '/',
		dest: config.paths.app,
		exportData: false,
		flatten: true,
		types: {
			data: {
				dir: '',
				files: [
					'core//*.hjson',
					'core//.json',
					// 'features/**/.hjson',
					// 'features//*.json',
					'shared/components//.hjson',
					'shared/components/**/.json',
					'pages//*.hjson',
					'pages//.json',
					'shared/utilities/**/.hjson',
					'shared/utilities//*.json'
				]
			},
			partials: {
				dir: '',
				files: [
					'shared/components//.hbs',
					'core/components/**/.hbs',
					// 'core/docs/components//*.hbs',
					// 'features//.hbs',
					'shared/utilities/**/.hbs'
				]
			},
			pages: {
				dir: '',
				files: pages
			},
			layouts: {
				dir: 'core',
				files: [
					'layouts/.hbs',
					'docs/layouts/.hbs'
				]
			}
		},
		helpers: [
			'shared/utilities/template-helpers/.js'
		]
	},
	dev: {
		options: {
			compileStaticFiles: false,
			devServer: {
				start: true,
				injectScript: false,
				useExt: true,
				port: config.ports.server,
				bsOptions: {
					proxy: 'localhost:' + config.ports.server,
					port: config.ports.app,
					files: [
						config.paths.app + '/**/.html',
						config.paths.app + '/css//*.css',
						config.paths.app + '/scripts//*.js'
					]
				}
			},
			watch: true
		}
	},
	dist: {
		options: {
			debug: true,
			compileStaticFiles: true,
			watch: false
		}
	}
};
```

I updated only the dist options. Hope it helps ...
