### ISSUE TITLE
cli component  genration not work after mangony update

### ISSUE THREAD

**Issue by natrenakres** [Sebastian-Fitzner/mangony#6]
Hi,

After mangony update new component is not working. Old components works but new components are not.  I added component module to  the app.js file  but new components are not trigger any event in Constructor or didMount etc. 

After that I update all cli veams and mangony but it is still not work. 

Did you change something?

OS: Windows 10 
Nodejs: 8.11.1
==================================================
@veams/generator-veams: 1.0.0-rc22
@veams/cli: 1.0.0-rc12
inserter: 1.1.3
==================================================

We add same component in Mac it works.

components code:

```
class Tcomponent extends Component {
	/**
	 * Class Properties
	 */
	$el = $(this.el);

	/**
	 * Constructor for our class
	 *
	 * @see module.js
	 *
	 * @param {Object} obj - Object which is passed to our class
	 * @param {Object} obj.el - element which will be saved in this.el
	 * @param {Object} obj.options - options which will be passed in as JSON object
	 */
	constructor(obj) {
		let options = {
			selectors: {	
			},
			classes: {}
		};

		super(obj, options);

		this.text = "Component Tcomponent mounted!";

		alert(this.text);
	}

	didMount() {
		alert(this.text);
	}

	/**
	 * Render class
	 */
	render() {
		alert("component will render");
		return this;
	}

	
}

// app.js file
Veams.modules.add({ namespace: "tcomponent", module: Tcomponent });
```

**Comment by Sebastian-Fitzner** [comment]
What do you mean with "not working"? Is it rendered into the markup? 
If so, it is not related to Mangony. 

If you do not get the js part running, it is more an issue related to Veams (https://github.com/Veams/core), but you need to post your package.json and setup.json so that I can at least filter down.

**Comment by natrenakres** [comment]
Yes it is rendered into the markap but no javascript interactions between markup and component class.  Ok i will close the issue and open it into veams/core repo.

**Comment by Sebastian-Fitzner** [comment]
okay nice, lets see how I can help out.
